version: "3.8"

services:
  prometheus:
    image: prom/prometheus:v2.44.0
    configs:
      - source: prometheus_config
        target: /etc/prometheus/prometheus.yml
    networks:
      - monitor-net
    ports:
      - "9090:9090"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  grafana:
    image: grafana/grafana:9.5.3
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=your_secure_password
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - monitor-net
    ports:
      - "3000:3000"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.1
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      - monitor-net
    deploy:
      mode: global

  node-exporter:
    image: prom/node-exporter:v1.6.0
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
    networks:
      - monitor-net
    deploy:
      mode: global

  fact_100k:
    image: devaimax/fact_100k:latest
    networks:
      - monitor-net
    deploy:
      replicas: 1

  fact_300k:
    image: devaimax/fact_300k:latest
    networks:
      - monitor-net
    deploy:
      replicas: 1

  fact_500k:
    image: devaimax/fact_500k:latest
    networks:
      - monitor-net
    deploy:
      replicas: 1

  matrix_4k:
    image: devaimax/matrix_4k:latest
    networks:
      - monitor-net
    deploy:
      replicas: 1

  matrix_5k:
    image: devaimax/matrix_5k:latest
    networks:
      - monitor-net
    deploy:
      replicas: 1

volumes:
  grafana-data:

networks:
  monitor-net:
    external: true
    name: monitor-net

configs:
  prometheus_config:
    file: ./prometheus.yml
